name: CI
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    strategy: 
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run build --if-present
      - run: yarn test
